// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAfoCF-cv2tyMOBX9juYAYT1X-tRw1Inw',
    appId: '1:177668992194:web:d16f5fe6720ffa28c71f5b',
    messagingSenderId: '177668992194',
    projectId: 'fintrack-ai-2c582',
    authDomain: 'fintrack-ai-2c582.firebaseapp.com',
    storageBucket: 'fintrack-ai-2c582.firebasestorage.app',
    measurementId: 'G-TN8X451QRL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLTaVn-1qaVYCBiKiLCEuFn_dJsbUBgRc',
    appId: '1:177668992194:android:c70b01ff5770b156c71f5b',
    messagingSenderId: '177668992194',
    projectId: 'fintrack-ai-2c582',
    storageBucket: 'fintrack-ai-2c582.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGGRy4L5HUrxvnubUCkAOyeLe7fbtZZiE',
    appId: '1:177668992194:ios:2e5c4c338d9457e2c71f5b',
    messagingSenderId: '177668992194',
    projectId: 'fintrack-ai-2c582',
    storageBucket: 'fintrack-ai-2c582.firebasestorage.app',
    iosClientId: '177668992194-m322kj9s10ihdjorf1922sv1a03s1n89.apps.googleusercontent.com',
    iosBundleId: 'com.fintrackai.fintrackAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGGRy4L5HUrxvnubUCkAOyeLe7fbtZZiE',
    appId: '1:177668992194:ios:2e5c4c338d9457e2c71f5b',
    messagingSenderId: '177668992194',
    projectId: 'fintrack-ai-2c582',
    storageBucket: 'fintrack-ai-2c582.firebasestorage.app',
    iosClientId: '177668992194-m322kj9s10ihdjorf1922sv1a03s1n89.apps.googleusercontent.com',
    iosBundleId: 'com.fintrackai.fintrackAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCAfoCF-cv2tyMOBX9juYAYT1X-tRw1Inw',
    appId: '1:177668992194:web:db09f29107c6181ac71f5b',
    messagingSenderId: '177668992194',
    projectId: 'fintrack-ai-2c582',
    authDomain: 'fintrack-ai-2c582.firebaseapp.com',
    storageBucket: 'fintrack-ai-2c582.firebasestorage.app',
    measurementId: 'G-LZSCR0J6M9',
  );
}
